-- =============================================================================
-- 019_gemini_embeddings.sql — switch embeddings to a free Gemini provider
--
-- The old pipeline embedded listings with OpenAI text-embedding-3-small
-- (VECTOR(1536)). To keep the platform on free models only, embeddings now
-- come from Google Gemini gemini-embedding-001 (768 dimensions, via
-- outputDimensionality) with a free Google AI Studio key. This migration:
--   1. Casts the existing column to vector(768).
--   2. Recreates the HNSW cosine index for the new dimensionality.
--   3. Rewrites match_properties to accept vector(768).
-- =============================================================================

-- 1) Drop the old HNSW index (built for 1536 dims) before changing the column
--    type so Postgres never has to rebuild it mid-migration.
DROP INDEX IF EXISTS idx_properties_embedding;

-- 2) Resize the column. Old OpenAI (1536-dim) vectors cannot be cast to
--    vector(768) and are semantically incompatible with Gemini embeddings
--    anyway, so they are reset to NULL and re-generated by
--    scripts/backfill-embeddings.mjs.
ALTER TABLE properties
  ALTER COLUMN embedding TYPE vector(768) USING NULL;

-- 3) Recreate the HNSW cosine index for the new dimensionality.
CREATE INDEX idx_properties_embedding
  ON properties USING hnsw (embedding vector_cosine_ops);

-- 4) Rewrite the semantic search RPC for 768-dim vectors.
DROP FUNCTION IF EXISTS public.match_properties(vector(1536), int);
DROP FUNCTION IF EXISTS public.match_properties(vector(768), int);

create or replace function public.match_properties(
  query_embedding vector(768),
  match_count int default 24
) returns table (
  id uuid,
  similarity float
) language plpgsql security definer
set search_path = public
as $$
begin
  return query
  select p.id, 1 - (p.embedding <=> query_embedding) as similarity
  from public.properties p
  where p.status = 'active'
    and p.embedding is not null
  order by p.embedding <=> query_embedding
  limit match_count;
end;
$$;

revoke all on function public.match_properties(vector(768), int) from public;
grant execute on function public.match_properties(vector(768), int) to authenticated;
grant execute on function public.match_properties(vector(768), int) to anon;
